### ISSUE TITLE
Error not receiving file

### ISSUE THREAD

**Issue by kim-do-hyeon** [kim-do-hyeon/Volaltility-gui#3]
Error getting <b>git clone https://github.com/volatilityfoundation/volatility3.git</b> when running <b>start.bat</b>

**Comment by kimbumyun98** [comment]
git clone은 git이 설치가 되어 있어야 실행된다.

start.bat 파일에서는 git을 설치하는 명령어가 들어있지 않아, 

git을 설치하는 명령어를 넣어줘야 한다.

git을 설치하는 과정은 처음에는 cmd 명령어로 다운을 받을려고 했는데

cmd로 git을 설치하는게 안나와서 choco를 이용하였다.

1. choco를 다운받아준다.
2. choco로 git을 다운받아준다.
3. volatility3.git을 설치해준다.

![image](https://user-images.githubusercontent.com/62227254/77228550-7e511e80-6bcb-11ea-83ef-467f881364d1.png)

**Comment by kim-do-hyeon** [comment]
All file changed, Delete start.bat
